spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.clf.blog.entity
    configuration:
      map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.clf.blog: debug
  #file: log/blog-dev.log

server:
  port: 80

comment.avatar: /images/avatar.jpg
